apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace | default "microservices" | quote }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.databaseUrl | quote }}
  JWT_SECRET_KEY: {{ .Values.jwtSecretKey | quote }}
