name: "EKS Infrastructure Lifecycle Management"

on:
  # 1. Allows manually triggering the workflow from the GitHub Actions UI tab
  workflow_dispatch:
    inputs:
      action:
        description: "Select Action to execute on AWS Infrastructure"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

  # 2. Automated Cron Schedule: Runs every night at 10:00 PM UTC (3:30 AM IST)
  schedule:
    - cron: "30 17 * * *"

jobs:
  manage-infrastructure:
    name: "Manage EKS Lifecycle"
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for passwordless AWS OpenID Connect (OIDC) auth
      contents: read

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4 # Clones repo files onto GitHub runner

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::526727148285:role/GitHubActionsTerraformRole # Replace with your IAM Role ARN
          aws-region: us-east-1

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Terraform Init
        run: terraform init # Connects to S3 remote backend state & locks

      # --- DESTROY EXECUTION ROUTE ---
      # Runs if triggered by scheduled cron OR if manual input action is 'destroy'
      - name: Terraform Destroy (Teardown EKS)
        if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.action == 'destroy')
        run: terraform destroy -auto-approve -var="enable_deletion_protection=false"

      # --- APPLY EXECUTION ROUTE ---
      # Runs ONLY if manually triggered with 'apply' input
      - name: Terraform Apply (Rebuild EKS)
        if: github.event_name == 'workflow_dispatch' && inputs.action == 'apply'
        run: terraform apply -auto-approve
